sudo: false
jobs:
  include:
    - stage: Tests
      os: osx
      language: objective-c
      osx_image: xcode10.1
      before_install:
        - nvm install 10.9.0
        - nvm use 10.9.0
        - rvm use 2.5.1 --install
      cache:
        bundler: true
        cocoapods: true
      script:
        - /bin/bash tests/travis.sh
    - stage: Tests
      os: linux
      jdk: oraclejdk8
      language: android
      before_install:
        - nvm install 10.9.0
        - nvm use 10.9.0
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-22
          - android-28
          - sys-img-armeabi-v7a-android-22
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
          - $HOME/.nvm
      script:
        - /bin/bash tests/travis.sh
    - stage: Build
      os: linux
      jdk: oraclejdk8
      language: android
      before_install:
        - nvm install 12.14.0
        - nvm use 12.14.0
        - rvm use 2.7.0 --install
        - /bin/bash demo/install.sh
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      cache:
        bundler: true
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
          - demo/node_modules
          - $HOME/.nvm
      script:
        - /bin/bash demo/travis.sh
stages:
  - Tests
  - name: Build
    if: type = pull_request

